#!/usr/bin/env bash
# redirecting script

sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://github.com/AlvinOt permanent;' /etc/nginx/sites-available/default

sudo service nginx restart
