#!/usr/bin/env bash
#load balancer installation
sudo apt-get -y update
apt-get -y install haproxy

# editing config_file
server_config=\
"
frontend  alvin-frontend
        bind *:80
        mode http
        default_backend alvin-backend
backend alvin-backend
        balance roundrobin
        server 172583-web-01 100.26.220.29 check
        server 172583-web-02 52.23.212.47 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
