#!/usr/bin/env bash
#load balancer installation

sudo apt-get update -y
sudo apt-get install -y haproxy

sudo sh -c 'echo "ENABLED=1" >> /etc/default/haproxy'

sudo sh -c 'cat << EOF >> /etc/haproxy/haproxy.cfg
frontend hbnbclone
    bind *:80
    option forwardfor
    default_backend alvinservers

backend alvinservers
    balance roundrobin
    server 172583-web-01 100.26.220.29:80 check
    server 172583-web-02 52.23.212.47:80 check
    option httpchk
    option httpclose
EOF'

sudo service haproxy start

