#!/usr/bin/env bash
#load balancer installation
#append to haproxy.cfg

#sudo apt-get update -y
#sudo apt-get install -y haproxy
#echo "ENABLED=1" >> /etc/default/haproxy
#mv /etc/haproxy/haproxy.cfg{,.original}
#touch /etc/haproxy/haproxy.cfg

#printf %s "
frontend  alvin-frontend
        bind *:80
        mode http
        default_backend alvin-backend
backend alvin-backend
        balance roundrobin
        server 172583-web-01 100.26.220.29:80 check
        server 172583-web-02 52.23.212.47:80 check
#" >> /etc/haproxy/haproxy.cfg

service haproxy start
