#!/usr/bin/env bash
# terminate Apache processes
pkill apache2

# change ownership of nginx.conf to nginx user and group
chown nginx:nginx /etc/nginx/nginx.conf

# set permissions for nginx.conf
chmod 777 /etc/nginx/nginx.conf

# replace occurrences of port 80 with 8080 in default Nginx site configuration
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# start Nginx service as the nginx user
sudo -u nginx service nginx start

